// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/grants": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grants"
                ],
                "summary": "Create a new grant (admin)",
                "parameters": [
                    {
                        "description": "Grant payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.createGrantRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/admin/grants/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "grants"
                ],
                "summary": "Archive a grant (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Grant UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grants"
                ],
                "summary": "Update a grant's mutable fields",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Grant UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.updateGrantRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/admin/grants/{id}/nofo": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grants"
                ],
                "summary": "Ingest NOFO document text for a grant (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Grant UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "NOFO text",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ingestNOFORequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/admin/leads": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "leads"
                ],
                "summary": "List all leads (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/admin/leads/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "leads"
                ],
                "summary": "Get a lead by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lead UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "leads"
                ],
                "summary": "Update a lead record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lead UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.updateLeadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/admin/leads/{id}/activities": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "leads"
                ],
                "summary": "Get activity timeline for a lead",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lead UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/admin/leads/{id}/convert": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "leads"
                ],
                "summary": "Convert a lead to a paying organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lead UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Target organization",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.convertLeadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/admin/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get aggregate platform statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/applications/{application_id}/narratives": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "narratives"
                ],
                "summary": "List AI narratives for an application",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application UUID",
                        "name": "application_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/applications/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Get a grant application by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Update application fields",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.updateApplicationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/applications/{id}/activities": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Get activity log for an application",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/applications/{id}/narratives": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Get all AI narratives for an application",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/applications/{id}/status": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Advance or change an application's pipeline status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New status",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.updateApplicationStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/auth/change-password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Change the authenticated user's password",
                "parameters": [
                    {
                        "description": "Change password payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.changePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authenticate and receive a JWT",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get the authenticated user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/auth/reset-password": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Reset password using a reset token",
                "parameters": [
                    {
                        "description": "Reset password payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.resetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Signup payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.signupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/grants": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grants"
                ],
                "summary": "List active grants",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page size (default 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated statuses",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/grants/search": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grants"
                ],
                "summary": "Search grants by title keyword",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/grants/semantic-search": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grants"
                ],
                "summary": "Semantic (vector) search for grants",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Free-text description",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of results (default 10)",
                        "name": "top_k",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/grants/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grants"
                ],
                "summary": "Get a grant by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Grant UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/leads": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "leads"
                ],
                "summary": "Capture a new lead (from quiz or landing page)",
                "parameters": [
                    {
                        "description": "Lead data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.captureLeadRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/orgs": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Create a new organization",
                "parameters": [
                    {
                        "description": "Organization data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.createOrgRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/orgs/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Get an organization by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Update an organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.updateOrgRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/orgs/{id}/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Get the detailed profile for an organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Create or update an organization's eligibility profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Profile data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.upsertProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/orgs/{org_id}/applications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "List applications for an organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "org_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Start tracking a grant application",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "org_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Application data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.createApplicationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/orgs/{org_id}/grants/{grant_id}/narratives": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "narratives"
                ],
                "summary": "Generate an AI narrative section for a grant application",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "org_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Grant UUID",
                        "name": "grant_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Generation parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.generateNarrativeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/orgs/{org_id}/grants/{grant_id}/score": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scoring"
                ],
                "summary": "Get stored compatibility score",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "org_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Grant UUID",
                        "name": "grant_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scoring"
                ],
                "summary": "Compute compatibility score for an org/grant pair",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "org_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Grant UUID",
                        "name": "grant_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/orgs/{org_id}/score-all": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scoring"
                ],
                "summary": "Trigger bulk scoring of all active grants for an org",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "org_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/orgs/{org_id}/top-grants": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scoring"
                ],
                "summary": "List top-scored grants for an organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "org_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Envelope"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_readygeneration_readygeneration-backend_internal_domain.CompetitionLevel": {
            "type": "string",
            "enum": [
                "low",
                "medium",
                "high",
                "very_high"
            ],
            "x-enum-varnames": [
                "CompetitionLow",
                "CompetitionMedium",
                "CompetitionHigh",
                "CompetitionVeryHigh"
            ]
        },
        "github_com_readygeneration_readygeneration-backend_internal_domain.DifficultyLevel": {
            "type": "string",
            "enum": [
                "easy",
                "medium",
                "hard",
                "very_hard"
            ],
            "x-enum-varnames": [
                "DifficultyEasy",
                "DifficultyMedium",
                "DifficultyHard",
                "DifficultyVeryHard"
            ]
        },
        "github_com_readygeneration_readygeneration-backend_internal_domain.FunderType": {
            "type": "string",
            "enum": [
                "federal",
                "state",
                "local",
                "private",
                "foundation",
                "corporate"
            ],
            "x-enum-varnames": [
                "FunderFederal",
                "FunderState",
                "FunderLocal",
                "FunderPrivate",
                "FunderFoundation",
                "FunderCorporate"
            ]
        },
        "github_com_readygeneration_readygeneration-backend_internal_domain.GrantStatus": {
            "type": "string",
            "enum": [
                "active",
                "closed",
                "archived",
                "draft"
            ],
            "x-enum-varnames": [
                "GrantStatusActive",
                "GrantStatusClosed",
                "GrantStatusArchived",
                "GrantStatusDraft"
            ]
        },
        "github_com_readygeneration_readygeneration-backend_pkg_response.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_readygeneration_readygeneration-backend_pkg_response.Envelope": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.APIError"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_pkg_response.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_readygeneration_readygeneration-backend_pkg_response.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_handler.captureLeadRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "city": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "interested_grants": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "last_name": {
                    "type": "string"
                },
                "org_name": {
                    "type": "string"
                },
                "org_type": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "quiz_responses": {
                    "type": "object",
                    "additionalProperties": true
                },
                "source": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "utm_campaign": {
                    "type": "string"
                },
                "utm_medium": {
                    "type": "string"
                },
                "utm_source": {
                    "type": "string"
                },
                "zip": {
                    "type": "string"
                }
            }
        },
        "internal_handler.changePasswordRequest": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "new_password": {
                    "type": "string",
                    "minLength": 8
                },
                "old_password": {
                    "type": "string"
                }
            }
        },
        "internal_handler.convertLeadRequest": {
            "type": "object",
            "required": [
                "org_id"
            ],
            "properties": {
                "org_id": {
                    "type": "string"
                }
            }
        },
        "internal_handler.createApplicationRequest": {
            "type": "object",
            "required": [
                "grant_id"
            ],
            "properties": {
                "assigned_to": {
                    "type": "string"
                },
                "grant_id": {
                    "type": "string"
                },
                "internal_deadline": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "priority": {
                    "type": "string"
                }
            }
        },
        "internal_handler.createGrantRequest": {
            "type": "object",
            "required": [
                "funder_name",
                "funder_type",
                "slug",
                "title"
            ],
            "properties": {
                "agency": {
                    "type": "string"
                },
                "application_url": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "competition_level": {
                    "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_internal_domain.CompetitionLevel"
                },
                "deadline": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "difficulty_level": {
                    "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_internal_domain.DifficultyLevel"
                },
                "eligible_org_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "eligible_populations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "eligible_states": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "focus_areas": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "funder_name": {
                    "type": "string"
                },
                "funder_type": {
                    "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_internal_domain.FunderType"
                },
                "match_percentage": {
                    "type": "number"
                },
                "max_award_amount": {
                    "type": "integer"
                },
                "min_award_amount": {
                    "type": "integer"
                },
                "open_date": {
                    "type": "string"
                },
                "requires_501c3": {
                    "type": "boolean"
                },
                "requires_audited_fin": {
                    "type": "boolean"
                },
                "requires_match": {
                    "type": "boolean"
                },
                "slug": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_readygeneration_readygeneration-backend_internal_domain.GrantStatus"
                },
                "synopsis": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "total_funding_available": {
                    "type": "integer"
                }
            }
        },
        "internal_handler.createOrgRequest": {
            "type": "object",
            "required": [
                "name",
                "org_type",
                "slug"
            ],
            "properties": {
                "city": {
                    "type": "string"
                },
                "ein": {
                    "type": "string"
                },
                "mission": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "org_type": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                },
                "zip": {
                    "type": "string"
                }
            }
        },
        "internal_handler.generateNarrativeRequest": {
            "type": "object",
            "required": [
                "section"
            ],
            "properties": {
                "application_id": {
                    "type": "string"
                },
                "custom_notes": {
                    "type": "string"
                },
                "section": {
                    "type": "string"
                },
                "word_target": {
                    "type": "integer"
                }
            }
        },
        "internal_handler.ingestNOFORequest": {
            "type": "object",
            "required": [
                "text"
            ],
            "properties": {
                "text": {
                    "type": "string"
                }
            }
        },
        "internal_handler.loginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_handler.resetPasswordRequest": {
            "type": "object",
            "required": [
                "new_password",
                "token"
            ],
            "properties": {
                "new_password": {
                    "type": "string",
                    "minLength": 8
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "internal_handler.signupRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "internal_handler.updateApplicationRequest": {
            "type": "object",
            "properties": {
                "award_amount": {
                    "type": "integer"
                },
                "internal_deadline": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "priority": {
                    "type": "string"
                },
                "stage": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "submission_date": {
                    "type": "string"
                }
            }
        },
        "internal_handler.updateApplicationStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "stage": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_handler.updateGrantRequest": {
            "type": "object",
            "properties": {
                "deadline": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "synopsis": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal_handler.updateLeadRequest": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "org_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_handler.updateOrgRequest": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "logo_url": {
                    "type": "string"
                },
                "mission": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                },
                "zip": {
                    "type": "string"
                }
            }
        },
        "internal_handler.upsertProfileRequest": {
            "type": "object",
            "properties": {
                "annual_budget": {
                    "type": "integer"
                },
                "focus_issues": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "has_501c3": {
                    "type": "boolean"
                },
                "has_audited_financials": {
                    "type": "boolean"
                },
                "has_indirect_cost_rate": {
                    "type": "boolean"
                },
                "indirect_cost_rate_pct": {
                    "type": "number"
                },
                "narrative": {
                    "type": "string"
                },
                "num_employees": {
                    "type": "integer"
                },
                "num_volunteers": {
                    "type": "integer"
                },
                "populations_served": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "prior_federal_grants": {
                    "type": "boolean"
                },
                "program_areas": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "service_areas": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "years_operating": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "ReadyGeneration API",
	Description:      "Grant intelligence platform API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
